#!/usr/bin/env bash
#This Script do infinity loop and send SIGKILL

echo "$$" > /var/run/myscript.pid

do_samething()
{
	echo "I hate the kill command"
	rm /var/run/myscript.pid
	exit 0
}

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me"' SIGINT
	trap do_samething SIGTERM SIGQUIT
done
