#!/usr/bin/env bash
#This using for the SIGTERM for termibated in process in exection 

id=$(pgrep -f 4-to_infinity_and_beyond)

if [[ -n "$id" ]]; then
	kill -15 "$id"
else
	echo "Process Not found"
fi

