#!/usr/bin/env bash
#This Script using understand more for the condition 

i=1
while [[ "$i" -le 20 ]]; do
	case "$i" in
		5) echo "bad luck from China" 
			echo "5" ;;
		10) echo "bad luck from Japan" 
			echo "10" ;;
		18) echo "bad luck from Italy"
			echo "18" ;;
		*) echo "$i" ;;
	esac
	i=$((i+1))
done
